# - if avpython interpreter found then the python lib has to be hat in his path

find_package(PythonInterp)
if(PYTHON_EXECUTABLE)
	get_filename_component(tmp ${PYTHON_EXECUTABLE} PATH)
	get_filename_component(PYTHON_MY_BASE_DIR ${tmp} PATH)
	message("PYTHON_LIBRARY-------->${PYTHON_LIBRARY}<-- PYTHON_MY_BASE_DIR--->${PYTHON_MY_BASE_DIR}<--")
	
	set(orig_CMAKE_FIND_ROOT_PATH ${CMAKE_FIND_ROOT_PATH})
	set(orig_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ${CMAKE_FIND_ROOT_PATH_MODE_PROGRAM})
	set(orig_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
	set(orig_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})
	message("---------------- CMAKE_FIND_ROOT_PATH------>  ${CMAKE_FIND_ROOT_PATH} ------------------")
	#set(CMAKE_FIND_ROOT_PATH ${PYTHON_MY_BASE_DIR} )
	#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
	#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
	#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
	
	include(${CMAKE_ROOT}/Modules/FindPythonLibs.cmake)

	set(CMAKE_FIND_ROOT_PATH ${orig_CMAKE_FIND_ROOT_PATH})
	set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ${orig_CMAKE_FIND_ROOT_PATH_MODE_PROGRAM})
	set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ${orig_CMAKE_FIND_ROOT_PATH_MODE_LIBRARY})
	set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ${orig_CMAKE_FIND_ROOT_PATH_MODE_INCLUDE})

endif()



