get_filename_component(currfolder ${CMAKE_CURRENT_LIST_FILE} PATH)
set(infile ${currfolder}/pkgconfig_lib_template-pc.in)
set(description "autogenerated pkg for package ${name}")
configure_file(${infile} ${prefix}/lib/pkgconfig/${pkgfilename}.pc @ONLY)

message("
prefix--->${prefix}<--
infile--->${infile}<--
name-->${libname}<--
infile-->${infile}<--
")

